### ISSUE TITLE
E24 Arch. Assessment Graph branching vs. desired form structure

### ISSUE THREAD

**Issue by mradamcox** [azerbini/eamena_dev#10]
The relevant portion of the Archaeological Assessment resource types's graphs looks like this

![image](https://user-images.githubusercontent.com/10427268/39328437-04932f54-4961-11e8-87ea-7111f2a24633.png)

The desired structure of the form is to group the Function and Interpretation nodes (**B**) into a single *interpretation* section and place the time-span nodes (**C**) in a separate *timespan* section. In `forms.py`, to make this grouping happen, *interpretation* must reference the **A** node, while *timespan* must reference **D**.

The problem is that this causes double branches to be created once the form is saved. For example

![image](https://user-images.githubusercontent.com/10427268/39328963-97c47c1e-4962-11e8-91b5-a3d244f60b33.png)

Wondering what the right way to handle a situation like this is, or if the graph/form format need to be altered.

**Comment by azerbini** [comment]
Hi Adam, I have encountered and solved this issue by calling the method `exclude_empty_branches` on form loads: https://github.com/azerbini/eamena_dev/blob/21e960c844a3f6a4d289cb9bc18e0423e1f6737d/eamena/eamena/models/forms.py#L68


this said, I think there is an error here in the E24 Interface doc, since I am pretty sure we had agreed among us that cultural periods and interpretations would be bound together into one 'Add'. Let me get back to you on this.

**Comment by mradamcox** [comment]
Ok. I see `exclude_empty_branches()` now, but it makes me wonder, wouldn't these empty branches affect the process of creating resource reports?

**Comment by azerbini** [comment]
Hi @mradamcox, so I discussed this internally and as I thought we want all these fields to be grouped into one 'add' section. This includes Function, Interpretation, Cultural period and Period of occupation. Consequently, there won't be any need for you to use the exclude_empty_branches logic.

**Comment by mradamcox** [comment]
Ok, just added a commit to the existing PR to address this.

**Comment by azerbini** [comment]
Thank you Adam. I will be hoping to merge all this on Friday as I am currently in Egypt for our training.
